Module6 task2
htmlacademy-nodejs/505149-buy-and-sell-3 pull request #16
Opened 2020-12-25 18:58 UTC by deniolp

2020-12-26 11:27 UTC, Krabaton requested changes

2020-12-26 11:27 UTC, Krabaton commented on src/service/api/offer.js
> +    const offer = await offerService.create(req.body);
Странно немного. Если будет ошибка при создании 
```
try {
      const offerCategories = await Category.findAll({
        where: {
          id: {
            [sequelize.Sequelize.Op.or]: categoriesIds,
          },
        }
      });

      const user = await User.findByPk(1);
      const newOffer = await user.createOffer(offer);
      await newOffer.addCategories(offerCategories);

      return await Offer.findByPk(newOffer.id, {raw: true});
    } catch (error) {
      this._logger.error(`Can not create offer. Error: ${error}`);

      return null;
    }
```
то на вернется null и мы отправим его со статусом 201 создано...

2020-12-26 11:27 UTC, Krabaton commented on src/service/api/offer.js
> +    const deletedComment = commentService.delete(commentId);
Это разве не асинхронная операция?

2020-12-26 11:27 UTC, Krabaton commented on src/service/api/offer.js
> +    const comment = commentService.create(offer.id, req.body);
Это разве не асинхронная операция?

2021-01-03 15:21 UTC, deniolp commented on src/service/api/offer.js
> +    const offer = await offerService.create(req.body);
Добавил недостающие проверки на null в роутере

2021-01-03 15:21 UTC, deniolp commented on src/service/api/offer.js
> +    const deletedComment = commentService.delete(commentId);
Ты абсолютно прав! Поправил!)

2021-01-03 15:21 UTC, deniolp commented on src/service/api/offer.js
> +    const comment = commentService.create(offer.id, req.body);
Готово)

2021-01-07 11:56 UTC, merged